services:
  watchtower:
    image: nickfedor/watchtower
    restart: unless-stopped
    command:
      - "--label-enable"
      - "--rolling-restart"
      - "--include-restarting"
      - "--stop-timeout"
      - "60s"
      - "--scope=smart-ringer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - REPO_USER=mikewon98
      - REPO_PASS=${GITHUB_TOKEN}
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=${DISCORD_WEBHOOK_URL}
  smart-ringer:
    image: ghcr.io/mikewon98/smart-ringer:stable
    restart: unless-stopped
    networks:
      - portfolio_default
    labels:
      - "traefik.enable=true"

      # Main HTTPS router
      - "traefik.http.routers.smart-ringer.rule=Host(`smartringer.michaelyze.com`)"
      - "traefik.http.routers.smart-ringer.entrypoints=websecure"
      - "traefik.http.routers.smart-ringer.tls.certresolver=myresolver"

      # HTTP redirect router
      - "traefik.http.routers.smart-ringer-http.rule=Host(`smartringer.michaelyze.com`)"
      - "traefik.http.routers.smart-ringer-http.middlewares=redirect-to-https-en"
      - "traefik.http.routers.smart-ringer-http.entrypoints=web"

      # Service configuration
      - "traefik.http.services.smart-ringer.loadbalancer.server.port=3000"

      # Middlewares
      - "traefik.http.middlewares.redirect-to-https-en.redirectscheme.permanent=true"
      - "traefik.http.middlewares.redirect-to-https-en.redirectscheme.scheme=https"

      # Rate limiting (protection against bots)
      - "traefik.http.middlewares.rate-limit.ratelimit.average=100"
      - "traefik.http.middlewares.rate-limit.ratelimit.burst=50"
      - "traefik.http.middlewares.rate-limit.ratelimit.period=1s"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=smart-ringer"

    env_file:
      - .env

networks:
  portfolio_default:
    external: true
